/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.studioblueplanet.tomtomwatch;


import net.studioblueplanet.usb.UsbFile;
import net.studioblueplanet.ttbin.TomTomReader;
import net.studioblueplanet.ttbin.Activity;
import net.studioblueplanet.ttbin.TtbinFileDefinition;
import net.studioblueplanet.ttbin.GpxWriter;
import net.studioblueplanet.logger.DebugLogger;
import net.studioblueplanet.settings.ConfigSettings;



import hirondelle.date4j.DateTime;
import java.io.File;
import javax.swing.BoxLayout;

import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;
import javax.swing.JOptionPane;


import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import net.studioblueplanet.usb.WatchInterface;
import org.jdesktop.application.ResourceMap;

/**
 * View for the TomTomWatch application. Supports Multisport,
 * Spark/Runner and Adventurer
 *
 * @author Jorgen
 */
public class TomTomWatchView extends javax.swing.JFrame
{
 
    private final CommunicationProcess          communicationProcess;
    
 
    private final ConfigSettings                settings;
    private final Map                           map;
    
    
    private TomTomWatchAbout                    aboutBox;
    
    private float                               trackSmoothingQFactor;
   
    /**
     * Constructor. Creates new form TomTomWatchView
     */
    public TomTomWatchView()
    {
        DefaultListModel            model;
        boolean                     trackSmoothing;
        
        TomTomReader                reader;
        
        // Get the application settings
        settings = ConfigSettings.getInstance();

        // Set the DebugLogger log level
        DebugLogger.setDebugLevel(settings.getStringValue("debugLevel"));

        // Initialize the widgents and components
        initComponents();
        
        // Initialize the listbox
        model = new DefaultListModel();
        this.jListActivities.setModel(model);
        this.jListActivities.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        // Set the TTBIN file path
        this.jTextFieldTtbinPath.setText(settings.getStringValue("ttbinFilePath"));
        
        // Set the autosave option
        this.jCheckBoxAutoSave.setSelected(settings.getBooleanValue("autoSaveTtbin"));

        // Initialize the map
        this.jPanelMap.setLayout(new BoxLayout(this.jPanelMap, BoxLayout.Y_AXIS));
        map = new Map(this.jPanelMap);

        // Fixed progress bar from 0-1000 promile
        this.jProgressBar.setMinimum(0);
        this.jProgressBar.setMaximum(1000);
        this.jProgressBar.setValue(0);

        if (!settings.getBooleanValue("debuggingMenu"))
        {
            this.jMenuDebugging.setVisible(false);
        }
        
        // Get the communication process. This starts the process
        communicationProcess=CommunicationProcess.getInstance(this);

        // Set the track smoothing to the TomTom TTBIN reader
        trackSmoothing          =settings.getBooleanValue("trackSmoothingEnabled");
        trackSmoothingQFactor   =(float)settings.getDoubleValue("trackSmoothingQFactor");
        this.jCheckBoxSmooth.setSelected(trackSmoothing);
        
        // If simulation data is used, disable the menu item to save simulation data
        if (settings.getBooleanValue("simulation"))
        {
            this.jMenuItemSaveSimSet.setEnabled(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaStatus = new javax.swing.JTextArea();
        jButtonDownload = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListActivities = new javax.swing.JList();
        jButtonErase = new javax.swing.JButton();
        jButtonUploadGps = new javax.swing.JButton();
        jPanelMap = new javax.swing.JPanel();
        jButtonSaveGpx = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTtbinPath = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCheckBoxAutoSave = new javax.swing.JCheckBox();
        jTextFieldGpxFile = new javax.swing.JTextField();
        jButtonChooseTtbinPath = new javax.swing.JButton();
        jButtonSaveTtbin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldWatch = new javax.swing.JTextField();
        jTextFieldTime = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jRadioButtonRunning = new javax.swing.JRadioButton();
        jRadioButtonCycling = new javax.swing.JRadioButton();
        jRadioButtonHiking = new javax.swing.JRadioButton();
        jRadioButtonSwimming = new javax.swing.JRadioButton();
        jRadioButtonSkating = new javax.swing.JRadioButton();
        jRadioButtonDriving = new javax.swing.JRadioButton();
        jRadioButtonFlying = new javax.swing.JRadioButton();
        jRadioButtonMulti = new javax.swing.JRadioButton();
        jProgressBar = new javax.swing.JProgressBar();
        jButtonLoadTtbin = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldRouteGpx = new javax.swing.JTextField();
        jTextFieldRouteName = new javax.swing.JTextField();
        jButtonChooseRoute = new javax.swing.JButton();
        jButtonUploadRoute = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButtonEraseRoutes = new javax.swing.JButton();
        jTextFieldFirmware = new javax.swing.JTextField();
        jTextFieldProductId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jCheckBoxSmooth = new javax.swing.JCheckBox();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemQuit = new javax.swing.JMenuItem();
        jMenuDevice = new javax.swing.JMenu();
        jMenuItemListRoutes = new javax.swing.JMenuItem();
        jMenuItemSetName = new javax.swing.JMenuItem();
        jMenuItemListHistorySummary = new javax.swing.JMenuItem();
        jMenuItemListHistory = new javax.swing.JMenuItem();
        jMenuItemEraseData = new javax.swing.JMenuItem();
        jMenuItemUpdateFirmware = new javax.swing.JMenuItem();
        jMenuItemListRaces = new javax.swing.JMenuItem();
        jMenuDebugging = new javax.swing.JMenu();
        jMenuItemPreferences = new javax.swing.JMenuItem();
        jMenuItemListFiles = new javax.swing.JMenuItem();
        jMenuDownloadFile = new javax.swing.JMenuItem();
        jMenuItemUploadFile = new javax.swing.JMenuItem();
        jMenuItemDeleteFile = new javax.swing.JMenuItem();
        jMenuItemReboot = new javax.swing.JMenuItem();
        jMenuItemSaveSimSet = new javax.swing.JMenuItem();
        jMenuItemShowUpdateLog = new javax.swing.JMenuItem();
        jMenuItemShowLog = new javax.swing.JMenuItem();
        jMenuItemPlaylists = new javax.swing.JMenuItem();
        jMenuItemShowTrackedActivity = new javax.swing.JMenuItem();
        jMenuDeleteTrackedActivity = new javax.swing.JMenuItem();
        jMenuAbout = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jMenuItem2.setText("jMenuItem2");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTextAreaStatus.setEditable(false);
        jTextAreaStatus.setColumns(20);
        jTextAreaStatus.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        jTextAreaStatus.setRows(5);
        jScrollPane1.setViewportView(jTextAreaStatus);

        jButtonDownload.setText("Download");
        jButtonDownload.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonDownloadActionPerformed(evt);
            }
        });

        jListActivities.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        jListActivities.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "x" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jListActivities.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                jListActivitiesValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(jListActivities);

        jButtonErase.setText("Erase");
        jButtonErase.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonEraseActionPerformed(evt);
            }
        });

        jButtonUploadGps.setText("GPS Quickfix");
        jButtonUploadGps.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonUploadGpsActionPerformed(evt);
            }
        });

        jPanelMap.setBackground(new java.awt.Color(230, 230, 230));

        javax.swing.GroupLayout jPanelMapLayout = new javax.swing.GroupLayout(jPanelMap);
        jPanelMap.setLayout(jPanelMapLayout);
        jPanelMapLayout.setHorizontalGroup(
            jPanelMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelMapLayout.setVerticalGroup(
            jPanelMapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        jButtonSaveGpx.setText("Save");
        jButtonSaveGpx.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonSaveGpxActionPerformed(evt);
            }
        });

        jLabel1.setText("TTBIN Path");

        jLabel2.setText("GPX File");

        jCheckBoxAutoSave.setText("Autosave");

        jButtonChooseTtbinPath.setText("Choose");
        jButtonChooseTtbinPath.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonChooseTtbinPathActionPerformed(evt);
            }
        });

        jButtonSaveTtbin.setText("Save TTBIN");
        jButtonSaveTtbin.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonSaveTtbinActionPerformed(evt);
            }
        });

        jLabel4.setText("TomTomWatch: ");

        jTextFieldWatch.setEditable(false);

        jTextFieldTime.setEditable(false);

        buttonGroup1.add(jRadioButtonRunning);
        jRadioButtonRunning.setText("Running");
        jRadioButtonRunning.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButtonRunningActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonCycling);
        jRadioButtonCycling.setText("Cycling");
        jRadioButtonCycling.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButtonCyclingActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonHiking);
        jRadioButtonHiking.setText("Hiking");
        jRadioButtonHiking.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButtonHikingActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonSwimming);
        jRadioButtonSwimming.setText("Swimming");
        jRadioButtonSwimming.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButtonSwimmingActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonSkating);
        jRadioButtonSkating.setText("Skating");
        jRadioButtonSkating.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButtonSkatingActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonDriving);
        jRadioButtonDriving.setText("Driving");
        jRadioButtonDriving.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButtonDrivingActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonFlying);
        jRadioButtonFlying.setText("Flying");
        jRadioButtonFlying.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButtonFlyingActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonMulti);
        jRadioButtonMulti.setText("Multi");
        jRadioButtonMulti.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jRadioButtonMultiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonSwimming)
                    .addComponent(jRadioButtonSkating)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonHiking)
                            .addComponent(jRadioButtonCycling)
                            .addComponent(jRadioButtonRunning))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonDriving)
                            .addComponent(jRadioButtonFlying)
                            .addComponent(jRadioButtonMulti))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonRunning)
                    .addComponent(jRadioButtonDriving))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonCycling)
                    .addComponent(jRadioButtonFlying))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonHiking)
                    .addComponent(jRadioButtonMulti))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonSwimming)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonSkating)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonLoadTtbin.setText("Load TTBIN");
        jButtonLoadTtbin.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonLoadTtbinActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Upload Route");

        jLabel3.setText("Route GPX");

        jLabel5.setText("Route name");

        jButtonChooseRoute.setText("Choose");
        jButtonChooseRoute.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonChooseRouteActionPerformed(evt);
            }
        });

        jButtonUploadRoute.setText("Upload");
        jButtonUploadRoute.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonUploadRouteActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Tracks & GPS Quickfix");

        jButtonEraseRoutes.setText("Erase");
        jButtonEraseRoutes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButtonEraseRoutesActionPerformed(evt);
            }
        });

        jTextFieldFirmware.setEditable(false);

        jTextFieldProductId.setEditable(false);

        jLabel8.setText("Product ID: ");

        jLabel9.setText("Firmware: ");

        jLabel10.setText("Time:");

        jCheckBoxSmooth.setText("Smooth");
        jCheckBoxSmooth.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCheckBoxSmoothActionPerformed(evt);
            }
        });

        jMenuFile.setText("File");

        jMenuItemQuit.setText("Quit");
        jMenuItemQuit.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemQuitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemQuit);

        jMenuBar.add(jMenuFile);

        jMenuDevice.setText("Device");

        jMenuItemListRoutes.setText("List Routes");
        jMenuItemListRoutes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemListRoutesActionPerformed(evt);
            }
        });
        jMenuDevice.add(jMenuItemListRoutes);

        jMenuItemSetName.setText("Set Device Name");
        jMenuItemSetName.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemSetNameActionPerformed(evt);
            }
        });
        jMenuDevice.add(jMenuItemSetName);

        jMenuItemListHistorySummary.setText("Activity Summary");
        jMenuItemListHistorySummary.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemListHistorySummaryActionPerformed(evt);
            }
        });
        jMenuDevice.add(jMenuItemListHistorySummary);

        jMenuItemListHistory.setText("Activity History");
        jMenuItemListHistory.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemListHistoryActionPerformed(evt);
            }
        });
        jMenuDevice.add(jMenuItemListHistory);

        jMenuItemEraseData.setText("Erase History");
        jMenuItemEraseData.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemEraseDataActionPerformed(evt);
            }
        });
        jMenuDevice.add(jMenuItemEraseData);

        jMenuItemUpdateFirmware.setText("Update Firmware");
        jMenuItemUpdateFirmware.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemUpdateFirmwareActionPerformed(evt);
            }
        });
        jMenuDevice.add(jMenuItemUpdateFirmware);

        jMenuItemListRaces.setText("List Races");
        jMenuItemListRaces.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemListRacesActionPerformed(evt);
            }
        });
        jMenuDevice.add(jMenuItemListRaces);

        jMenuBar.add(jMenuDevice);

        jMenuDebugging.setText("Debugging");

        jMenuItemPreferences.setText("Preferences");
        jMenuItemPreferences.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemPreferencesActionPerformed(evt);
            }
        });
        jMenuDebugging.add(jMenuItemPreferences);

        jMenuItemListFiles.setText("List All Files");
        jMenuItemListFiles.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemListFilesActionPerformed(evt);
            }
        });
        jMenuDebugging.add(jMenuItemListFiles);

        jMenuDownloadFile.setText("Download File");
        jMenuDownloadFile.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuDownloadFileActionPerformed(evt);
            }
        });
        jMenuDebugging.add(jMenuDownloadFile);

        jMenuItemUploadFile.setText("Upload File");
        jMenuItemUploadFile.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemUploadFileActionPerformed(evt);
            }
        });
        jMenuDebugging.add(jMenuItemUploadFile);

        jMenuItemDeleteFile.setText("Delete File");
        jMenuItemDeleteFile.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemDeleteFileActionPerformed(evt);
            }
        });
        jMenuDebugging.add(jMenuItemDeleteFile);

        jMenuItemReboot.setText("Reboot Watch");
        jMenuItemReboot.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemRebootActionPerformed(evt);
            }
        });
        jMenuDebugging.add(jMenuItemReboot);

        jMenuItemSaveSimSet.setText("Save Simulation Set");
        jMenuItemSaveSimSet.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemSaveSimSetActionPerformed(evt);
            }
        });
        jMenuDebugging.add(jMenuItemSaveSimSet);

        jMenuItemShowUpdateLog.setText("Show Update Log");
        jMenuItemShowUpdateLog.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemShowUpdateLogActionPerformed(evt);
            }
        });
        jMenuDebugging.add(jMenuItemShowUpdateLog);

        jMenuItemShowLog.setText("Show Device Log");
        jMenuItemShowLog.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemShowLogActionPerformed(evt);
            }
        });
        jMenuDebugging.add(jMenuItemShowLog);

        jMenuItemPlaylists.setText("Playlists");
        jMenuItemPlaylists.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemPlaylistsActionPerformed(evt);
            }
        });
        jMenuDebugging.add(jMenuItemPlaylists);

        jMenuItemShowTrackedActivity.setText("Show Tracked Activity");
        jMenuItemShowTrackedActivity.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemShowTrackedActivityActionPerformed(evt);
            }
        });
        jMenuDebugging.add(jMenuItemShowTrackedActivity);

        jMenuDeleteTrackedActivity.setText("Delete Tracked Activity");
        jMenuDeleteTrackedActivity.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuDeleteTrackedActivityActionPerformed(evt);
            }
        });
        jMenuDebugging.add(jMenuDeleteTrackedActivity);

        jMenuBar.add(jMenuDebugging);

        jMenuAbout.setText("Help");
        jMenuAbout.setToolTipText("");
        jMenuAbout.setActionCommand("");

        jMenuItemAbout.setText("About");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenuAbout.add(jMenuItemAbout);

        jMenuBar.add(jMenuAbout);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jButtonDownload, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonErase, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonUploadGps, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonLoadTtbin)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonSaveTtbin, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(34, 34, 34)
                                                .addComponent(jTextFieldGpxFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextFieldTtbinPath, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButtonChooseTtbinPath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonSaveGpx, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckBoxAutoSave)
                                            .addComponent(jCheckBoxSmooth))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldRouteName, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldRouteGpx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonChooseRoute)
                                    .addComponent(jButtonUploadRoute)))
                            .addComponent(jButtonEraseRoutes, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldWatch)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTime, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldFirmware, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldProductId, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jPanelMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonDownload, jButtonErase, jButtonLoadTtbin, jButtonSaveTtbin, jButtonUploadGps});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonChooseRoute, jButtonEraseRoutes, jButtonUploadRoute});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldRouteGpx, jTextFieldRouteName});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldGpxFile, jTextFieldTtbinPath});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldWatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFirmware, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldProductId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(jPanelMap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonDownload)
                            .addComponent(jButtonErase)
                            .addComponent(jButtonUploadGps)
                            .addComponent(jButtonLoadTtbin)
                            .addComponent(jButtonSaveTtbin))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldTtbinPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jButtonChooseTtbinPath)
                            .addComponent(jCheckBoxAutoSave))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jTextFieldGpxFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonSaveGpx))
                            .addComponent(jCheckBoxSmooth)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextFieldRouteGpx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonChooseRoute))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(jTextFieldRouteName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonUploadRoute))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonEraseRoutes))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDownloadActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonDownloadActionPerformed
    {//GEN-HEADEREND:event_jButtonDownloadActionPerformed
        boolean trackSmoothingEnabled;
        
        // Set the tracksmoothing
        trackSmoothingEnabled=this.jCheckBoxSmooth.isSelected();
        communicationProcess.setTrackSmoothing(trackSmoothingEnabled, trackSmoothingQFactor);
        
        // Do the download
        checkAndPushCommand(ThreadCommand.THREADCOMMAND_DOWNLOAD);
    }//GEN-LAST:event_jButtonDownloadActionPerformed

    private void jRadioButtonRunningActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButtonRunningActionPerformed
    {//GEN-HEADEREND:event_jRadioButtonRunningActionPerformed
        updateActivityInfo(true);
    }//GEN-LAST:event_jRadioButtonRunningActionPerformed

    private void jListActivitiesValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_jListActivitiesValueChanged
    {//GEN-HEADEREND:event_jListActivitiesValueChanged
        if (!evt.getValueIsAdjusting())
        {
            updateActivityInfo(false);
        }
    }//GEN-LAST:event_jListActivitiesValueChanged

    private void jRadioButtonCyclingActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButtonCyclingActionPerformed
    {//GEN-HEADEREND:event_jRadioButtonCyclingActionPerformed
        updateActivityInfo(true);
    }//GEN-LAST:event_jRadioButtonCyclingActionPerformed

    private void jRadioButtonHikingActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButtonHikingActionPerformed
    {//GEN-HEADEREND:event_jRadioButtonHikingActionPerformed
        updateActivityInfo(true);
    }//GEN-LAST:event_jRadioButtonHikingActionPerformed

    private void jRadioButtonSwimmingActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButtonSwimmingActionPerformed
    {//GEN-HEADEREND:event_jRadioButtonSwimmingActionPerformed
        updateActivityInfo(true);
    }//GEN-LAST:event_jRadioButtonSwimmingActionPerformed

    private void jRadioButtonSkatingActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButtonSkatingActionPerformed
    {//GEN-HEADEREND:event_jRadioButtonSkatingActionPerformed
        updateActivityInfo(true);
    }//GEN-LAST:event_jRadioButtonSkatingActionPerformed

    private void jRadioButtonDrivingActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButtonDrivingActionPerformed
    {//GEN-HEADEREND:event_jRadioButtonDrivingActionPerformed
        updateActivityInfo(true);
    }//GEN-LAST:event_jRadioButtonDrivingActionPerformed

    private void jRadioButtonFlyingActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButtonFlyingActionPerformed
    {//GEN-HEADEREND:event_jRadioButtonFlyingActionPerformed
        updateActivityInfo(true);
    }//GEN-LAST:event_jRadioButtonFlyingActionPerformed

    private void jRadioButtonMultiActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jRadioButtonMultiActionPerformed
    {//GEN-HEADEREND:event_jRadioButtonMultiActionPerformed
        updateActivityInfo(true);
    }//GEN-LAST:event_jRadioButtonMultiActionPerformed

    private void jMenuItemQuitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemQuitActionPerformed
    {//GEN-HEADEREND:event_jMenuItemQuitActionPerformed
        // Signal the thread to bail out
        communicationProcess.requestStop();
        // Remove the JFrame
        this.dispose();
    }//GEN-LAST:event_jMenuItemQuitActionPerformed

    private void jButtonEraseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonEraseActionPerformed
    {//GEN-HEADEREND:event_jButtonEraseActionPerformed
        int response;
        
        if (communicationProcess.isConnected())
        {
            response = JOptionPane.showConfirmDialog(null, "Do you want to erase TTBIN files from the watch?", "Confirm",
                                                     JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_OPTION) 
            {
                // Signal the thread to erase the files
                communicationProcess.pushCommand(ThreadCommand.THREADCOMMAND_DELETETTBINFILES);
            } 
            else 
            {

            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No watch connected", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEraseActionPerformed

    private void jButtonUploadGpsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonUploadGpsActionPerformed
    {//GEN-HEADEREND:event_jButtonUploadGpsActionPerformed
        // Signal the thread to upload GPS data for quick GPS fix
        checkAndPushCommand(ThreadCommand.THREADCOMMAND_UPLOADGPSDATA);
    }//GEN-LAST:event_jButtonUploadGpsActionPerformed

    private void jButtonChooseTtbinPathActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonChooseTtbinPathActionPerformed
    {//GEN-HEADEREND:event_jButtonChooseTtbinPathActionPerformed
        JFileChooser                fc;
        String                      directoryName;
        int                         returnValue;
        
        fc= new JFileChooser();
        
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        
        directoryName=this.jTextFieldTtbinPath.getText();
        if (directoryName.equals(""))
        {
            fc.setCurrentDirectory(new File(settings.getStringValue("ttbinFilePath")));
        }
        else
        {
            fc.setCurrentDirectory(new File(directoryName));
        }
        
        returnValue=fc.showDialog(null, "Select");
        
        if (returnValue == JFileChooser.APPROVE_OPTION)
        {
            directoryName=fc.getSelectedFile().toString();
            
            this.jTextFieldTtbinPath.setText(directoryName);
        }
        if (returnValue == JFileChooser.CANCEL_OPTION)
        {

        }  

    }//GEN-LAST:event_jButtonChooseTtbinPathActionPerformed

    private void jButtonSaveGpxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonSaveGpxActionPerformed
    {//GEN-HEADEREND:event_jButtonSaveGpxActionPerformed
        int                         index;
        ActivityData                data;
        Activity                    activity;
        GpxWriter                   writer;
        String                      fileName;
        String                      path;
        String                      appName;
        
        TomTomWatch     app;
        ResourceMap     appResourceMap;

        app=TomTomWatch.getApplication();

        appResourceMap=app.getContext().getResourceMap();
        appName="TomTomWatch "+appResourceMap.getString("Application.version");
        
        
        
        index = this.jListActivities.getSelectedIndex();
        
        data=communicationProcess.getActivityData(index);
        
        if (data!=null)
        {
            activity=data.activity;

            
            fileName=this.jTextFieldGpxFile.getText();
            path    =settings.getStringValue("gpxFilePath");
            
            fileName=this.fileChooser(fileName, path, "Save", "GPX files (*.gpx)", "gpx");

            if (fileName!=null)
            {
                
                writer=GpxWriter.getInstance();
                writer.writeTrackToFile(fileName, activity, appName);                
            }
            
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No track selected", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSaveGpxActionPerformed

    /**
     * Saves the selected TTBIN file
     * @param evt 
     */
    private void jButtonSaveTtbinActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonSaveTtbinActionPerformed
    {//GEN-HEADEREND:event_jButtonSaveTtbinActionPerformed
        int                 index;
        ActivityData        data;
        Activity            activity;
        UsbFile             file;
        TtbinFileWriter     writer;
        String              ttbinPath;
        String              description;
        DefaultListModel    model;
        String              fileName;
        boolean             fileSaveError;

        
        
        index   = this.jListActivities.getSelectedIndex();

        data=communicationProcess.getActivityData(index);
        
        if (data!=null)
        {
            activity        =data.activity;
            file            =data.file;
            writer          =TtbinFileWriter.getInstance();
            // Get the ttbin root path
            ttbinPath       =this.jTextFieldTtbinPath.getText();
            
            
            // Create the subpath (if it does not already exist) in tomtom style:
            // <watchname>/<date>/ and generate the filename: 
            // <watchname>/<date>/<activity>_<time>.ttbin
            // TODO: handle illegal ttbinpath value, e.g. ""
            fileName        =writer.getFullFileName(ttbinPath, 
                                                    communicationProcess.getDeviceName(), 
                                                    activity.getStartDateTime(), 
                                                    activity.getActivityDescription());
         
            if (fileName!=null)
            {
                fileName=this.fileChooser(fileName, null, "Save", "TTBIN files (*.ttbin)", "ttbin");
                if (fileName!=null)
                {
                    // Write the file
                    fileSaveError=writer.writeTtbinFile(fileName, file);
                    
                    // If succeeded, check the file on disk
                    if (!fileSaveError)
                    {
                        fileSaveError=writer.verifyTtbinFile(fileName, file);
                        
                        // If validated, update the listbox
                        if (!fileSaveError)
                        {
                            data.ttbinSaved=true;
                            // Add the activity info to the listbox
                            description = getActivityDescription(data, "watch: ");
                            model       = (DefaultListModel) this.jListActivities.getModel();
                            model.set(index, description);
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(this, "Verification of TTBIN file failed", "Error", JOptionPane.ERROR_MESSAGE);
                        }
                    }                    
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Error writing TTBIN file", "Warning", JOptionPane.ERROR_MESSAGE);
            }
            
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No track selected", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSaveTtbinActionPerformed

    private void jMenuItemPreferencesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemPreferencesActionPerformed
    {//GEN-HEADEREND:event_jMenuItemPreferencesActionPerformed
        checkAndPushCommand(ThreadCommand.THREADCOMMAND_PREFERENCES);

    }//GEN-LAST:event_jMenuItemPreferencesActionPerformed

    private void jMenuItemListFilesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemListFilesActionPerformed
    {//GEN-HEADEREND:event_jMenuItemListFilesActionPerformed
        checkAndPushCommand(ThreadCommand.THREADCOMMAND_LISTFILES);
    }//GEN-LAST:event_jMenuItemListFilesActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemAboutActionPerformed
    {//GEN-HEADEREND:event_jMenuItemAboutActionPerformed
        TomTomWatch     app;
        ResourceMap     appResourceMap;

        app=TomTomWatch.getApplication();

        appResourceMap=app.getContext().getResourceMap();

        if (aboutBox == null)
        {
            //            JFrame mainFrame = UgotmeApp.getApplication().getMainFrame();
            aboutBox = new TomTomWatchAbout(this, true);
            aboutBox.setLocationRelativeTo(this);

            aboutBox.setVersion(appResourceMap.getString("Application.version"));
            aboutBox.setAuthor(appResourceMap.getString("Application.author"));
            aboutBox.setHomePage(appResourceMap.getString("Application.homepage"));
        }
        TomTomWatch.getApplication().show(aboutBox);
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void jMenuItemSetNameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemSetNameActionPerformed
    {//GEN-HEADEREND:event_jMenuItemSetNameActionPerformed
        String name;
        
        if (communicationProcess.isConnected())
        {
            name = JOptionPane.showInputDialog(this, "Give new Device Name", communicationProcess.getDeviceName());
            if (name!=null)
            {
               name=name.trim();
               if (!name.equals(""))
               {
                   
                   communicationProcess.requestSetNewDeviceName(name);
               }
               else
               {
                    JOptionPane.showMessageDialog(this, "No name entered", "Warning", JOptionPane.WARNING_MESSAGE);
               }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No watch connected", "Warning", JOptionPane.WARNING_MESSAGE);            
        }
        
    }//GEN-LAST:event_jMenuItemSetNameActionPerformed

    private void jButtonLoadTtbinActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonLoadTtbinActionPerformed
    {//GEN-HEADEREND:event_jButtonLoadTtbinActionPerformed
        String              fileName;
        String              ttbinPath;
        int                 listItems;
        boolean trackSmoothingEnabled;
        
        // Set the tracksmoothing
        trackSmoothingEnabled=this.jCheckBoxSmooth.isSelected();
        communicationProcess.setTrackSmoothing(trackSmoothingEnabled, trackSmoothingQFactor);        

        ttbinPath=this.jTextFieldTtbinPath.getText();

        
        fileName=this.fileChooser(ttbinPath, null, "Load", "TTBIN files (*.ttbin)", "ttbin");
        
        if (fileName!=null)
        {
            communicationProcess.loadActivityFromTtbinFile(fileName);
        }
    }//GEN-LAST:event_jButtonLoadTtbinActionPerformed

    /**
     * This method handles the menu item requesting saving 
     * a watch file to disk
     */
    private void jMenuDownloadFileActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuDownloadFileActionPerformed
    {//GEN-HEADEREND:event_jMenuDownloadFileActionPerformed
        String  hex;
        int     fileId;
        
        if (communicationProcess.isConnected())
        {
            hex = JOptionPane.showInputDialog(this, "Give new file ID (hex)", "");
            if (hex!=null)
            {
               hex=hex.trim();
               hex=hex.toLowerCase();
               if (!hex.equals(""))
               {
                   hex=hex.replace("0x", "");
                   
                   try
                   {
                       fileId=Integer.parseInt(hex, 16);
                       communicationProcess.requestWriteDeviceFileToDisk(fileId);
                   }
                   catch (NumberFormatException e)
                   {
                       JOptionPane.showMessageDialog(this, "Cannot parse file ID", "Error", JOptionPane.ERROR_MESSAGE);
                   }
               }
               else
               {
                    JOptionPane.showMessageDialog(this, "No ID entered", "Warning", JOptionPane.WARNING_MESSAGE);
               }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No watch connected", "Warning", JOptionPane.WARNING_MESSAGE);            
        }
        
        
    }//GEN-LAST:event_jMenuDownloadFileActionPerformed

    private void jMenuItemListHistorySummaryActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemListHistorySummaryActionPerformed
    {//GEN-HEADEREND:event_jMenuItemListHistorySummaryActionPerformed
        checkAndPushCommand(ThreadCommand.THREADCOMMAND_LISTHISTORYSUMMARY);
    }//GEN-LAST:event_jMenuItemListHistorySummaryActionPerformed

    private void jButtonChooseRouteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonChooseRouteActionPerformed
    {//GEN-HEADEREND:event_jButtonChooseRouteActionPerformed
        String              fileName;
        String              path;
        GpxReader           reader;
        Route               route;
        File                file;
        String              name;
        boolean             error;
        
        fileName=this.jTextFieldRouteGpx.getText();
        path    =settings.getStringValue("routeFilePath");
        
        fileName=this.fileChooser(fileName, path, "Load", "GPX files (*.gpx)", "gpx");
        
        if (fileName!=null)
        {
            this.jTextFieldRouteGpx.setText(fileName);
            
            // If the name of the route not set, 
            // take the filename without the extension as name
            name=this.jTextFieldRouteName.getText();
            if (name.equals(""))
            {
                file=new File(fileName);
                name=file.getName();
                name=name.replace(".gpx", "");
                name=name.replace(".GPX", "");
                this.jTextFieldRouteName.setText(name);
            }
            // Read the route
            reader=GpxReader.getInstance();

            // The log contains now the route read
            route=new RouteTomTom();

            error=reader.readRouteFromFile(fileName, route);
            map.showTrack(route);
            this.jListActivities.clearSelection();

        }
    }//GEN-LAST:event_jButtonChooseRouteActionPerformed

    private void jButtonUploadRouteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonUploadRouteActionPerformed
    {//GEN-HEADEREND:event_jButtonUploadRouteActionPerformed
        String name;
        String file;
        
        if (communicationProcess.isConnected())
        {
            name=this.jTextFieldRouteName.getText().trim();
            file=this.jTextFieldRouteGpx.getText().trim();

            if (!name.equals(""))
            {
                if (!file.equals(""))
                {
                    communicationProcess.requestUploadGpxFile(file, name);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "No gpx file entered", "Warning", JOptionPane.WARNING_MESSAGE); 
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "No name entered", "Warning", JOptionPane.WARNING_MESSAGE); 
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No watch connected", "Warning", JOptionPane.WARNING_MESSAGE);            
        }
    }//GEN-LAST:event_jButtonUploadRouteActionPerformed

    /**
     * List routes button event handler
     * @param evt Event
     */
    private void jMenuItemListRoutesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemListRoutesActionPerformed
    {//GEN-HEADEREND:event_jMenuItemListRoutesActionPerformed
        checkAndPushCommand(ThreadCommand.THREADCOMMAND_LISTROUTES);
    }//GEN-LAST:event_jMenuItemListRoutesActionPerformed

    /**
     * Erase route button event handler
     * @param evt Event
     */
    private void jButtonEraseRoutesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButtonEraseRoutesActionPerformed
    {//GEN-HEADEREND:event_jButtonEraseRoutesActionPerformed
        int response;
        
        if (communicationProcess.isConnected())
        {
            response = JOptionPane.showConfirmDialog(null, "Do you want to erase all route files from the watch?", "Confirm",
                                                     JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_OPTION) 
            {
                // Signal the thread to erase the files
                communicationProcess.pushCommand(ThreadCommand.THREADCOMMAND_CLEARROUTES);
                communicationProcess.pushCommand(ThreadCommand.THREADCOMMAND_LISTROUTES);
            } 
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No watch connected", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEraseRoutesActionPerformed

    /**
     * Menu item: erase all track and history data
     * @param evt Event
     */
    private void jMenuItemEraseDataActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemEraseDataActionPerformed
    {//GEN-HEADEREND:event_jMenuItemEraseDataActionPerformed
        int response;
        
        if (communicationProcess.isConnected())
        {
            response = JOptionPane.showConfirmDialog(null, "Do you want to erase all track, route and history data?", "Confirm",
                                                     JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_OPTION) 
            {
                 communicationProcess.pushCommand(ThreadCommand.TRHEADCOMMAND_CLEARDATA);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No watch connected", "Warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jMenuItemEraseDataActionPerformed

    private void jMenuItemListHistoryActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemListHistoryActionPerformed
    {//GEN-HEADEREND:event_jMenuItemListHistoryActionPerformed
        this.checkAndPushCommand(ThreadCommand.THREADCOMMAND_LISTHISTORY);
    }//GEN-LAST:event_jMenuItemListHistoryActionPerformed

    private void jMenuItemUpdateFirmwareActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemUpdateFirmwareActionPerformed
    {//GEN-HEADEREND:event_jMenuItemUpdateFirmwareActionPerformed
        this.checkAndPushCommand(ThreadCommand.THREADCOMMAND_UPDATEFIRMWARE);
    }//GEN-LAST:event_jMenuItemUpdateFirmwareActionPerformed

    private void jMenuItemDeleteFileActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemDeleteFileActionPerformed
    {//GEN-HEADEREND:event_jMenuItemDeleteFileActionPerformed
        String  hex;
        int     fileId;
        
        if (communicationProcess.isConnected())
        {
            hex = JOptionPane.showInputDialog(this, "Give new file ID (hex)", "");
            if (hex!=null)
            {
               hex=hex.trim();
               hex=hex.toLowerCase();
               if (!hex.equals(""))
               {
                   hex=hex.replace("0x", "");
                   
                   try
                   {
                       fileId=Integer.parseInt(hex, 16);
                       communicationProcess.requestDeleteDeviceFileFromWatch(fileId);
                   }
                   catch (NumberFormatException e)
                   {
                       JOptionPane.showMessageDialog(this, "Cannot parse file ID", "Error", JOptionPane.ERROR_MESSAGE);
                   }
               }
               else
               {
                    JOptionPane.showMessageDialog(this, "No ID entered", "Warning", JOptionPane.WARNING_MESSAGE);
               }
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No watch connected", "Warning", JOptionPane.WARNING_MESSAGE);            
        }
        
    }//GEN-LAST:event_jMenuItemDeleteFileActionPerformed

    private void jMenuItemSaveSimSetActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemSaveSimSetActionPerformed
    {//GEN-HEADEREND:event_jMenuItemSaveSimSetActionPerformed
        this.checkAndPushCommand(ThreadCommand.THREADCOMMAND_SAVESIMULATIONSET);
    }//GEN-LAST:event_jMenuItemSaveSimSetActionPerformed

    private void jMenuItemShowUpdateLogActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemShowUpdateLogActionPerformed
    {//GEN-HEADEREND:event_jMenuItemShowUpdateLogActionPerformed
        communicationProcess.requestShowFile(WatchInterface.FILEID_UPDATE_LOG);
    }//GEN-LAST:event_jMenuItemShowUpdateLogActionPerformed

    private void jMenuItemShowLogActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemShowLogActionPerformed
    {//GEN-HEADEREND:event_jMenuItemShowLogActionPerformed
        communicationProcess.requestShowFile(WatchInterface.FILEID_LOG);
    }//GEN-LAST:event_jMenuItemShowLogActionPerformed

    private void jCheckBoxSmoothActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCheckBoxSmoothActionPerformed
    {//GEN-HEADEREND:event_jCheckBoxSmoothActionPerformed
        // Clear the list of activities as maintained by the communication
        // process. En passant the listbox in this view is erased.
        communicationProcess.clear();
    }//GEN-LAST:event_jCheckBoxSmoothActionPerformed

    private void jMenuItemPlaylistsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemPlaylistsActionPerformed
    {//GEN-HEADEREND:event_jMenuItemPlaylistsActionPerformed
        communicationProcess.requestShowFile(WatchInterface.FILEID_PLAYLIST);
    }//GEN-LAST:event_jMenuItemPlaylistsActionPerformed

    private void jMenuItemListRacesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemListRacesActionPerformed
    {//GEN-HEADEREND:event_jMenuItemListRacesActionPerformed
        this.checkAndPushCommand(ThreadCommand.THREADCOMMAND_LISTRACES);
    }//GEN-LAST:event_jMenuItemListRacesActionPerformed

    private void jMenuItemShowTrackedActivityActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemShowTrackedActivityActionPerformed
    {//GEN-HEADEREND:event_jMenuItemShowTrackedActivityActionPerformed
        this.checkAndPushCommand(ThreadCommand.THREADCOMMAND_LISTTRACKEDACTIVITY);
    }//GEN-LAST:event_jMenuItemShowTrackedActivityActionPerformed

    private void jMenuDeleteTrackedActivityActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuDeleteTrackedActivityActionPerformed
    {//GEN-HEADEREND:event_jMenuDeleteTrackedActivityActionPerformed
        int response;
        
        if (communicationProcess.isConnected())
        {
            response = JOptionPane.showConfirmDialog(null, "Do you want to erase the tracked activity from the watch?", "Confirm",
                                                     JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_OPTION) 
            {
                // Signal the thread to erase the files
                communicationProcess.pushCommand(ThreadCommand.THREADCOMMAND_DELETETRACKEDACTIVITY);
            } 
            else 
            {

            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No watch connected", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuDeleteTrackedActivityActionPerformed

    private void jMenuItemUploadFileActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemUploadFileActionPerformed
    {//GEN-HEADEREND:event_jMenuItemUploadFileActionPerformed
        String fileName;
        
        
        if (communicationProcess.isConnected())
        {
            fileName="";

            fileName=this.fileChooser(fileName, null, "Upload", "bin (*.bin)", "bin");
            if (fileName!=null)
            {
                communicationProcess.requestUploadFile(fileName);
            }
        }        
    }//GEN-LAST:event_jMenuItemUploadFileActionPerformed

    private void jMenuItemRebootActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItemRebootActionPerformed
    {//GEN-HEADEREND:event_jMenuItemRebootActionPerformed
        int response;
        
        if (communicationProcess.isConnected())
        {
            response = JOptionPane.showConfirmDialog(null, "Do you want to reboot the watch?", "Confirm",
                                                     JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_OPTION) 
            {
                // Signal the thread to erase the files
                communicationProcess.pushCommand(ThreadCommand.THREADCOMMAND_REBOOT);
            } 
            else 
            {

            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No watch connected", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemRebootActionPerformed

    /*############################################################################################*\
     * HELPER FUNCTIONS     
    \*############################################################################################*/    

    /**
     * This method pushes a command on the command stack. First however a check 
     * is made whether a watch is connected
     * @param command The command to push.
     */
    private void checkAndPushCommand(ThreadCommand command)
    {
        if (communicationProcess.isConnected())
        {
            communicationProcess.pushCommand(command);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "No watch connected", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
    }
    
    /**
     * Returns the activity description to be shown in the list box. Format is:
     * [v] - [start datetime] [id] - [type] [activity]
     * [v]              - 'v': File has been saved, 'x': file has not been saved
     * [start datetime] - Start of the activity
     * [id]             - 0x99999999, file ID
     * [type]           - 'file' for loaded from file, 'watch' for downloaded from watch
     * [activity]       - the activity: 'run', 'swim' etc
     * @param data Data defining the activity
     * @param prefix Prefix indicating the source of the activity ('file' or 'watch')
     * @return A string with the description
     */
    public String getActivityDescription(ActivityData data, String prefix)
    {
        String      description;
        String      dateTime;

        if (data.ttbinSaved)
        {
            description = "v ";
        } else
        {
            description = "x ";
        }
        dateTime = data.activity.getStartDateTime().format("YYYY-MM-DD hh:mm:ss");
        description += String.format("0x%08x - ", data.file.fileId) + dateTime
                + " - " + prefix+String.format("%s", data.activity.getActivityDescription());

        return description;
    }

    
    
    
    /**
     * Based on the information in the activity, set the corresponding
     * radio button
     * @param activity The activity for which the radio button is set
     */
    private void setRadioButton(Activity activity)
    {
        int activityType;

        activityType = activity.getActivityType();

        switch (activityType)
        {
            case TtbinFileDefinition.ACTIVITY_HIKING:
                this.jRadioButtonHiking.setSelected(true);
                break;
            case TtbinFileDefinition.ACTIVITY_CYCLING:
                this.jRadioButtonCycling.setSelected(true);
                break;
            case TtbinFileDefinition.ACTIVITY_RUNNING:
            case TtbinFileDefinition.ACTIVITY_TRAILRUNNING:
                this.jRadioButtonRunning.setSelected(true);
                break;
            default:
                this.jRadioButtonMulti.setSelected(true);
                break;
        }

    }

    /**
     * Generate the output file name based on the activity and selected activity
     * type (radio button)
     *
     * @param activity The activity to base the filename on
     */
    private void generateGpxFileName(Activity activity)
    {
        String      fileName;
        String      currentFileName;
        String      activityPrefix;
        String      path;
        String      file;
        String      fileTail;
        DateTime    timeStamp;

        if (this.jRadioButtonRunning.isSelected())
        {
            activityPrefix = "run";
        } else if (this.jRadioButtonCycling.isSelected())
        {
            activityPrefix = "cycle";
        } else if (this.jRadioButtonHiking.isSelected())
        {
            activityPrefix = "walk";
        } else if (this.jRadioButtonSwimming.isSelected())
        {
            activityPrefix = "swim";
        } else if (this.jRadioButtonDriving.isSelected())
        {
            activityPrefix = "drive";
        } else if (this.jRadioButtonFlying.isSelected())
        {
            activityPrefix = "flight";
        } else if (this.jRadioButtonSkating.isSelected())
        {
            activityPrefix = "skate";
        } else if (this.jRadioButtonMulti.isSelected())
        {
            activityPrefix = "multi";
        } else
        {
            activityPrefix = "unknown";
        }

        // Get the currently entered filename
        currentFileName = this.jTextFieldGpxFile.getText();

        // If the filename has not been defined yet, fill in the defaults
        if (currentFileName.equals(""))
        {

            fileName = settings.getStringValue("gpxFilePath");

            if ((!fileName.endsWith("/")) && (!fileName.endsWith("\\")))
            {
                fileName += "/";
            }
            fileName += activityPrefix + "_";

            timeStamp = activity.getStartDateTime();
            fileName += timeStamp.format("YYYYMMDD") + "_description.gpx";

            this.jTextFieldGpxFile.setText(fileName);
        } 
        else
        {
            file = currentFileName.replaceFirst("(^.*[/\\\\])?([^/\\\\]*)$", "$2");
            path = currentFileName.replaceFirst("(^.*[/\\\\])?([^/\\\\]*)$", "$1");

            fileTail = file.replaceFirst("^([a-z]*)([_]\\d{8})([_]\\S+)", "$3");

            timeStamp = activity.getStartDateTime();

            if (!fileTail.equals(file))
            {

                fileName = path + activityPrefix + "_" + timeStamp.format("YYYYMMDD") + fileTail;
                this.jTextFieldGpxFile.setText(fileName);
            }
        }
            
    }
    
  
    

    /**
     * Updates the GPX filename and optionally the map and radiobuttons
     * @param fileNameOnly True if only the GPX filename needs to be updated
     */
    private void updateActivityInfo(boolean fileNameOnly)
    {
        int             index;
        ActivityData    data;

        index   = this.jListActivities.getSelectedIndex();
        data    = communicationProcess.getActivityData(index);
        if (data != null)
        {
            if (!fileNameOnly)
            {
                map.showTrack(data);              // Show the map
                setRadioButton(data.activity);          // Set the appropriate radiobutton
            }
            generateGpxFileName(data.activity);         // Propose GPX file name
        }
    }

    /**
     * File Chooser functionality
     * @param initialFileName
     * @param buttonText
     * @param filterDescription
     * @param filterExtension
     * @return 
     */
    private String fileChooser(String initialFileName, String initialDirectory, String buttonText, String filterDescription, String filterExtension)
    {
        JFileChooser                fc;
        FileNameExtensionFilter     fileFilter;
        int                         returnValue;

        String                      path;
        String                      fileName;
        File                        theFile;
        
        fileName=null;
        
        fc= new JFileChooser();


        
        if (initialFileName.equals("") && initialDirectory!=null)
        {
            fc.setCurrentDirectory(new File(initialDirectory));
        }
        else
        {
            theFile=new File(initialFileName);
            path=theFile.getAbsolutePath();
            fc.setSelectedFile(new File(path));
        }
        
        

        fileFilter=new FileNameExtensionFilter(filterDescription, filterExtension);

        // Set file extension filters
        fc.addChoosableFileFilter(fileFilter);
        fc.setFileFilter(fileFilter);

        returnValue=fc.showDialog(null, buttonText);

        if (returnValue == JFileChooser.APPROVE_OPTION)
        {
            path=fc.getCurrentDirectory().toString();
            fileName=path+"/"+fc.getSelectedFile().getName();

            // Make sure the file has the right extension
            if(!fileName.toLowerCase().endsWith("."+filterExtension))
            {
                fileName +="."+filterExtension;
            }

        }
        if (returnValue == JFileChooser.CANCEL_OPTION)
        {
            
        }    
        
        return fileName;
    }
    
    
    
    /* ******************************************************************************************* *\
     * PUBLIC WIDGET FUNCTIONS
    \* ******************************************************************************************* */

    /**
     * Clears existing data and the UI
     */
    public void clear()
    {
        DefaultListModel model;

        // Clear the list 
        model = (DefaultListModel) this.jListActivities.getModel();
        model.clear();

        // Hide the map
        map.hideTrack();
    }
    
    /**
     * Displays the time in the time text box
     * @param time DateTime to show
     */
    public void showTime(DateTime time)
    {
        this.jTextFieldTime.setText(time.format("hh:mm:ss"));
    }

    /**
     * Set the progress bar
     * @param promile Progress in the range of 0-1000 
     */
    public void setProgress(int promile)
    {
        this.jProgressBar.setValue(promile);
    }
    
    /**
     * Set the status in the status area
     * @param status String to display
     */
    public void setStatus(String status)
    {
        this.jTextAreaStatus.setText(status);
    }
    
    /**
     * This method appends the line of status text to the status area, 
     * leaving any existing text in tact
     * @param status The line to append
     */
    public void appendStatus(String status)
    {
        this.jTextAreaStatus.append(status);
    }
    
    /**
     * Returns whether the ttbin autosave checkbox is checked
     * @return True when autosave checked, false if no
     */
    public boolean isAutoSaveTtbin()
    {
        return this.jCheckBoxAutoSave.isSelected();
    }
    /**
     * Returns the ttbin path
     * @return The TTBIN path
     */
    public String getTtbinPath()
    {
        return this.jTextFieldTtbinPath.getText();
    }

    /**
     * Adds item to the tracklist
     * @param data The item to add
     * @param prefix Prefix indicating the source of the data: 'file' or 'watch'
     */
    public void addListItem(ActivityData data, String prefix)
    {
        DefaultListModel    model;
        String              description;
        
        // Add the activity info to the listbox
        description = getActivityDescription(data, prefix);
        model       = (DefaultListModel) this.jListActivities.getModel();
        model.addElement(description);        
    }

    
    /**
     * Selects the last list item. 
     */
    public void selectLastListIndex()
    {
        int listItems;
        
        listItems=jListActivities.getModel().getSize();
        jListActivities.setSelectedIndex(listItems-1);
    }
    
    /**
     * Sets the device name
     * @param deviceName Name of the device 
     */
    public void setDeviceName(String deviceName)
    {
        this.jTextFieldWatch.setText(deviceName);
    }
    
    /**
     * Sets the firmware version in the appropriate text filed
     * @param version String defining the firmware
     */
    public void setFirmwareVersion(String version)
    {
        this.jTextFieldFirmware.setText(version);
    }
    
    public void setProductId(int id)
    {
        this.jTextFieldProductId.setText(String.format("0x%08x", id));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonChooseRoute;
    private javax.swing.JButton jButtonChooseTtbinPath;
    private javax.swing.JButton jButtonDownload;
    private javax.swing.JButton jButtonErase;
    private javax.swing.JButton jButtonEraseRoutes;
    private javax.swing.JButton jButtonLoadTtbin;
    private javax.swing.JButton jButtonSaveGpx;
    private javax.swing.JButton jButtonSaveTtbin;
    private javax.swing.JButton jButtonUploadGps;
    private javax.swing.JButton jButtonUploadRoute;
    private javax.swing.JCheckBox jCheckBoxAutoSave;
    private javax.swing.JCheckBox jCheckBoxSmooth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jListActivities;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenuAbout;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuDebugging;
    private javax.swing.JMenuItem jMenuDeleteTrackedActivity;
    private javax.swing.JMenu jMenuDevice;
    private javax.swing.JMenuItem jMenuDownloadFile;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemDeleteFile;
    private javax.swing.JMenuItem jMenuItemEraseData;
    private javax.swing.JMenuItem jMenuItemListFiles;
    private javax.swing.JMenuItem jMenuItemListHistory;
    private javax.swing.JMenuItem jMenuItemListHistorySummary;
    private javax.swing.JMenuItem jMenuItemListRaces;
    private javax.swing.JMenuItem jMenuItemListRoutes;
    private javax.swing.JMenuItem jMenuItemPlaylists;
    private javax.swing.JMenuItem jMenuItemPreferences;
    private javax.swing.JMenuItem jMenuItemQuit;
    private javax.swing.JMenuItem jMenuItemReboot;
    private javax.swing.JMenuItem jMenuItemSaveSimSet;
    private javax.swing.JMenuItem jMenuItemSetName;
    private javax.swing.JMenuItem jMenuItemShowLog;
    private javax.swing.JMenuItem jMenuItemShowTrackedActivity;
    private javax.swing.JMenuItem jMenuItemShowUpdateLog;
    private javax.swing.JMenuItem jMenuItemUpdateFirmware;
    private javax.swing.JMenuItem jMenuItemUploadFile;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelMap;
    private javax.swing.JProgressBar jProgressBar;
    private javax.swing.JRadioButton jRadioButtonCycling;
    private javax.swing.JRadioButton jRadioButtonDriving;
    private javax.swing.JRadioButton jRadioButtonFlying;
    private javax.swing.JRadioButton jRadioButtonHiking;
    private javax.swing.JRadioButton jRadioButtonMulti;
    private javax.swing.JRadioButton jRadioButtonRunning;
    private javax.swing.JRadioButton jRadioButtonSkating;
    private javax.swing.JRadioButton jRadioButtonSwimming;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaStatus;
    private javax.swing.JTextField jTextFieldFirmware;
    private javax.swing.JTextField jTextFieldGpxFile;
    private javax.swing.JTextField jTextFieldProductId;
    private javax.swing.JTextField jTextFieldRouteGpx;
    private javax.swing.JTextField jTextFieldRouteName;
    private javax.swing.JTextField jTextFieldTime;
    private javax.swing.JTextField jTextFieldTtbinPath;
    private javax.swing.JTextField jTextFieldWatch;
    // End of variables declaration//GEN-END:variables
}
